---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/13rentgen/grafana-annotations-bot

steps:
- name: build
  pull: always
  image: golang:1.11-alpine
  environment:
    GO111MODULE: on
  commands:
  - apk add -U git make
  - make build
  - make fmt
  - make vet
  - make lint
  when:
    event:
    - push
    - tag
    - pull_request

- name: release
  pull: default
  image: golang:1.11-alpine
  environment:
    GO111MODULE: on
  commands:
  - apk add -U git make
  - make release
  when:
    event:
    - tag

- name: github
  pull: default
  image: plugins/github-release
  settings:
    files: "dist/*"
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag